# Outputs generated by main.tf
output "ssh_key_name" {
    description = "SSH Key for instance login"
    value = "${alicloud_key_pair.ecs-example-ssh-key.key_file}"
}

output "user_login" {
    description = "Login name for ECS instance"
    value = "root"
}

output "public_ip" {
    description = "ECS instance public IP address"
    value = "${alicloud_instance.ecs-example-instance.public_ip}"
}

